spring:
  cloud:
    stream:
      function:
        definition : paymentProcessor # consume function name
      bindings:
        paymentProcessor-in-0 :
          destination: order-event  # key name consume
        paymentProcessor-out-0:
          destination: payment-event


server:
  port: 8082