spring:
  cloud:
    stream:
      function:
        definition : orderSupplier;paymentEventConsumer  #publist, consume function name
      bindings:
        orderSupplier-out-0:
          destination: order-event  # key name publish
        paymentEventConsumer-in-0 :
          destination: payment-event



server:
  port: 8081